In [134]:
import numpy as np
import os
import pickle

In [140]:
matrixA = np.array([[2, -7],
                    [5, 4]])

matrixB = np.array([[6, 1],
                    [4, -3]])

vectorF = np.array([4, 1])

print("Matrix A:")
print(matrixA)
print("Matrix B:")
print(matrixB)
print("Vector:")
print(vectorF)

Matrix A:
[[ 2 -7]
 [ 5  4]]
Matrix B:
[[ 6  1]
 [ 4 -3]]
Vector:
[4 1]


In [136]:
print("Size of matrixA:", matrixA.shape)
print("Size of vector:", vectorF.shape)

Size of matrixA: (2, 2)
Size of vector: (2,)


In [137]:
matrixB_T = matrixB.T
print("Transpose of matrixB:")
print(matrixB_T)

Transpose of matrixB:
[[ 6  4]
 [ 1 -3]]


In [123]:
matrixC = np.dot((matrixA + matrixB), (matrixA + matrixB)) + 2 * (matrixA - matrixB)
print("Answer:")
print(matrixC)

Answer:
[[  2 -70]
 [ 83 -39]]


In [124]:
matrixC = np.hstack((matrixA, matrixB))
vectorH = np.hstack((vectorF, vectorF))
print("Matrix C:")
print(matrixC)
print("Vector H:")
print(vectorH)

Matrix C:
[[ 2 -7  6  1]
 [ 5  4  4 -3]]
Vector H:
[4 1 4 1]


In [125]:
matrixC = np.dot(matrixC, vectorH)
print("Matrix C * Vector H:")
print(matrixC)

Matrix C * Vector H:
[26 37]


In [126]:
for name, value in locals().items():
    print(f"{name} = {value}")

__name__ = __main__
__doc__ = Automatically created module for IPython interactive environment
__package__ = None
__loader__ = None
__spec__ = None
__builtin__ = <module 'builtins' (built-in)>
__builtins__ = <module 'builtins' (built-in)>
__ = 
___ = 
__session__ = Basics.ipynb
var = _i96
sys = <module 'sys' (built-in)>
remove_imported_pydev_package = <function remove_imported_pydev_package at 0x0000018128126A20>
_pydevd_bundle = <module '_pydevd_bundle' from 'C:\\Users\\stszy\\AppData\\Local\\Programs\\PyCharm Professional\\plugins\\python\\helpers\\pydev\\_pydevd_bundle\\__init__.py'>
pydev_jupyter_vars = <module 'pydev_jupyter_vars' from 'C:\\Users\\stszy\\AppData\\Local\\Programs\\PyCharm Professional\\plugins\\python\\helpers-pro\\jupyter_debug\\pydev_jupyter_vars.py'>
_i = matrixC = np.dot(matrixC, vectorH)
print("Matrix C * Vector H:")
print(matrixC)
_ii = matrixC = np.hstack((matrixA, matrixB))
vectorH = np.hstack((vectorF, vectorF))
print("Matrix C:")
print(matrixC)
print("Vec

In [127]:
with open("data.txt", "w") as f:
    for key, value in globals().items():
        if not key.startswith("__"):
            f.write(f"{key} = {value}\n")

In [128]:
for var in list(globals().keys()):
    if not var.startswith("__"):
        del globals()[var]
        

In [129]:

for name, value in locals().items():
    print(f"{name} = {value}")

__name__ = __main__


RuntimeError: dictionary changed size during iteration

In [142]:
vectorX = np.arange(1, 25)
print("Vector X:")
print(vectorX)

Vector X:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [143]:
matrixY = vectorX.reshape(4, 6)
print("Matrix Y:")
print(matrixY)

Matrix Y:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [144]:
ans = np.exp(2 * np.sin(2 * np.pi))
print("Answer:")
print(ans)

Answer:
0.9999999999999996


In [145]:
ans = np.cos(np.pi/3)**4
print("Answer:")
print(ans)

Answer:
0.06250000000000006


In [146]:
ans = np.log(5**(1/2))
print("Answer:")
print(ans)

Answer:
0.8047189562170503


In [147]:
z = 3 - 2j
print("Complex number:")
print(z)
print("Argument:")
print(np.angle(z))
print("Conjugate:")
print(np.conjugate(z))


Complex number:
(3-2j)
Argument:
-0.5880026035475675
Conjugate:
(3+2j)


In [149]:
matrix1 = np.ones((10, 10))
print(matrix1);
matrix0 = np.zeros((10, 10))
print(matrix0);
matrixRand = np.random.rand(10, 10)
print(matrixRand);

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.50987112 0.88996005 0.47617614 0.66264207 0.79362637 0.71628644
  0.16219585 0.58228015 0.07534655 0.6599165 ]
 [0.51197201 0.95584897 0.29214709 0.59689031 0.73506658 0.89887843
  0.26362413 0.17850222 0.96580421 0.44202474]
 [0.77655582 0.47601522 0.04975507 0.29392908 0.02947672 0.04128319
  0.89486505 0.42778522 0.74777545 0.040